### ISSUE TITLE
Select moves from games using a distribution function.

### ISSUE THREAD

**Issue by singaurav** [singaurav/chess-engine#1]
The idea is to create a subclass of class **Game** and add a calculated field to store selected moves of the winner. Selections just at the beginning of the game or toward the end are not that useful, so there must be a bias to select aggressively from middle game.  Perhaps a configurable normal distribution will work.

**Comment by singaurav** [comment]
This now reduces to implementing 
`void GameWithPickedMoves::pick_moves<NORMAL>(unsigned count)` in gameinfo.cpp

**Comment by jiteshk23** [comment]
How are randomly selected moves from a game useful for us? Isn't any move very much dependent on the state of the board (i.e the moves that precede them) at that move?

On a seperate note, I read through the code to understand the task and had some suggestions. I have emailed you the notes.

**Comment by singaurav** [comment]
We are doing sampling of moves from a Game. So if Game is Start State Mw1, Mb1, Mw2, Mb2 ...... where Mw denotes white move and Mb black move. The idea is to sample some of the moves of the winner. These sampled moves will then define our training data. How? Suppose we sampled a move m and it was made on a state S. We first find out all legal moves at S. The winner chose this sampled move and ignored the rest of the alternative Moves. So we can say state generated by moving as per picked move should be better than a state generated by moving as per any other alternative move. Why - This is for the training data to come from a larger number of Games. Also such sampling allows us to choose the sampling bias. Ideally we should sample from middle game more because start game the things are very open and there can be a lot of good moves and in the end game the game is pretty much decided.
