### ISSUE TITLE
Ability to serialize sampled move continuation.

### ISSUE THREAD

**Issue by singaurav** [singaurav/chess-engine#12]

**Comment by jiteshk23** [comment]
@singaurav Hey, can you give some details here? I can pick this one next.

**Comment by singaurav** [comment]
Suppose we have a sampled move m and its alternate moves a1, a2, a3. We want to generate engine self play continuation lines for each move. This will look like below:
m m1 m2 m3 m4 - resulting in board state SM
a1 a11 a12 a13 a14 - resulting in board state SA1
...
an an1 an2 an3 an4 - resulting in board state SAN
these continuation lines actually get us to states(SM, SA1 .. SAN) which are comparable. 
One catch here is that it is possible that in one particular line the game got over before length K(4 above). We have to be able to distinguish these scenarios and deal with them separately. Maybe we can ignore these scenarios completely and drop the sampled move. Also engine strength, depth etc. should be configurable so we can try various combinations out. Hope this makes it clearer.

**Comment by jiteshk23** [comment]
ok so my understanding is as follows. Let say index 5 is the only samped move, then a GameWithSelfPlayContinuations can be serialized as follows.

```
Moves
1
2
.
.
SampledMoves
5 wm bm
AltMoves
5 wm1 bm1 wm2 bm2 .... wmN bmN
SelfPlayContinuations
5
wm+1 bm+1 .......... // considered only if game doesn't finish after 'n' moves
wm1+1 bm1+1 .........
wm2+1 bm2+1 .........
.
.
wmN+1 bmN+1 .........
```

**Comment by singaurav** [comment]
Format looks good.

**Comment by jiteshk23** [comment]
Hey @singaurav Can you explain the output of the genmoves command or is there any documentation I can read through?
```
<uciok>
<a2a3>
<b2b3>
<c2c3>
<d2d3>
<g2g3>
<h2h3>
<a2a4>
<b2b4>
<c2c4>
<d2d4>
<g2g4>
<h2h4>
<b1a3>
<b1c3>
<f3g1>
<f3d4>
<f3h4>
<f3e5>
<f3g5>
<f1e2>
<f1d3>
<f1c4>
<f1b5>
<f1a6>
<h1g1>
<d1e2>
<e1e2>
<info depth 1 seldepth 1 multipv 1 score cp 88 nodes 33 nps 16500 tbhits 0 time 2 pv d2d4>
<info depth 2 seldepth 2 multipv 1 score cp 102 nodes 94 nps 47000 tbhits 0 time 2 pv d2d4 d6d5 f3e5 d5e4>
<info depth 3 seldepth 3 multipv 1 score cp 114 nodes 196 nps 65333 tbhits 0 time 3 pv b1c3 c7c6 d2d4>
<info depth 4 seldepth 4 multipv 1 score cp 133 nodes 277 nps 69250 tbhits 0 time 4 pv b1c3 c7c6 d2d4 e5d4 d1d4>
<info depth 5 seldepth 5 multipv 1 score cp 72 nodes 1003 nps 125375 tbhits 0 time 8 pv b1c3 c7c5 h2h4 f7f5 h4h5 f5e4>
<info depth 6 seldepth 6 multipv 1 score cp 88 nodes 1530 nps 139090 tbhits 0 time 11 pv b1c3 c7c5 f1e2 c8g4 e1g1 a7a6>
<info depth 7 seldepth 8 multipv 1 score cp 134 nodes 3765 nps 188250 tbhits 0 time 20 pv b1c3 h7h6 d2d4 e5d4 d1d4 c8d7 d4d5>
<bestmove b1c3 ponder h7h6>
```

**Comment by singaurav** [comment]
http://support.stockfishchess.org/kb/advanced-topics/uci-protocol
http://wbec-ridderkerk.nl/html/UCIProtocol.html
